### ISSUE TITLE
ios 无法显示搜索下拉框

### ISSUE THREAD

**Issue by MouseSun846** [JQiue/vuepress-plugin-meilisearch2#1]
ios 无法显示搜索下拉框

**Comment by JQiue** [comment]
在其他客户端正常吗，我没有 ios 设备

**Comment by MouseSun846** [comment]
安卓 win 正常

**Comment by MouseSun846** [comment]
移动端与windows都是正常的，能不能适配下？

https://github.com/JQiue/vuepress-plugin-meilisearch2/assets/46400044/4e3dbc78-1b1b-49cf-9dfa-753f6bd9154e

**Comment by JQiue** [comment]
我可能需要找到 ios 设备才能确定问题，这个问题可能得不到及时处理

**Comment by MouseSun846** [comment]
好的谢谢你

**Comment by MouseSun846** [comment]
能加个微信吗？我的wx账号：KomorebiTimothy

**Comment by JQiue** [comment]
新版本已发，请测试

**Comment by MouseSun846** [comment]
> 新版本已发，请测试
没有看到有代码提交啊？能给出变更的代码吗

**Comment by JQiue** [comment]
> > 新版本已发，请测试
> 没有看到有代码提交啊？能给出变更的代码吗
> 

更新npm版本就行了

**Comment by MouseSun846** [comment]
> > > 新版本已发，请测试
> > > 没有看到有代码提交啊？能给出变更的代码吗
> 
> 更新npm版本就行了

我目前使用的是 npm -version  10.2.4， 你这边推荐使用版本是多少？

**Comment by JQiue** [comment]
> > > > 新版本已发，请测试
> > > > 没有看到有代码提交啊？能给出变更的代码吗
> > 
> > 更新npm版本就行了
> 
> 我目前使用的是 npm -version  10.2.4， 你这边推荐使用版本是多少？
> 

我说的是更新插件版本

**Comment by MouseSun846** [comment]
![image](https://github.com/JQiue/vuepress-plugin-meilisearch2/assets/46400044/92e7fd9c-5670-47ac-9892-ea38f3f10145)
我看你这个代码仓没有发布新的版本啊？最新的提交还是三周之前。

**Comment by MouseSun846** [comment]
我刚才去 https://www.npmjs.com/package/vuepress-plugin-meilisearch2?activeTab=readme 看到有新版本发布，请问修改的后的代码不打算开源吗？我在这个插件源码加了搜索结果过滤，如果用上面发布的，没法实现我的功能。希望你开源下最新的修改的代码，谢谢你

**Comment by JQiue** [comment]
我没有push到github，插件是支持结果过滤的，详情见meiliseach官网，我在这里只关注在ios有么有这个bug，然后关闭这个issue

**Comment by MouseSun846** [comment]
好的
