### ISSUE TITLE
默认vuepress2适配

### ISSUE THREAD

**Issue by sixmillions** [JQiue/vuepress-plugin-meilisearch2#2]
你好，我想给你提交个PR的 -- 适配一下vuepress2

但是我看仓库里面的代码和npmjs.org的对不上

![image](https://github.com/JQiue/vuepress-plugin-meilisearch2/assets/41658874/8cc58b09-a4df-40b7-8173-3c966e39c909)

适配思路如下

![image](https://github.com/JQiue/vuepress-plugin-meilisearch2/assets/41658874/149d321f-fbd7-475c-b934-d5420127290b)

componentName别写死，换成可以配置的

只要配置为 “SearchBox” ，就可以在vuepress2使用了

**Comment by JQiue** [comment]
我没有push到github，稍后push
